### ISSUE TITLE
Unable to send IPv6 address in edns field

### ISSUE THREAD

**Issue by yegle** [ayanamist/gdns-go#1]
Apparently Taobao's API doesn't support IPv6 address.

A good alternative would be a simple app running on App Engine which support both IPv4 and IPv6

**Comment by slgray** [comment]
一个建议，IP地址这个信息是否可以写在配置文件中。拨号上网虽然IP地址会变，但是这个变动对DNS解析影响不大。作为一个可选的配置项是否是一个简单直接的方式。

**Comment by yegle** [comment]
@slgray It looks like you can set a `myip` field in config.

**Comment by slgray** [comment]
看了config.go 好像是可以的，在 config-example.json 里面没有提到，明天试试。Thanks

**Comment by ayanamist** [comment]
对，config.json里可以设置。有一些隐藏特性，懒得写出来。
没有免费又耐操还支持IPv6的endpoint啊。 @yegle 你有推荐吗？
