### ISSUE TITLE
请问有没有 SS 的开关选项？

### ISSUE THREAD

**Issue by jzp820927** [ayanamist/gdns-go#5]
我想直接连接 Google HTTPS DNS，而不通过 ShadowSocks，请问有没有配置项能关闭 ShadowSocks，而直接访问 Google HTTPS DNS？

**Comment by ayanamist** [comment]
配置里proxy填空字符串即可。

**Comment by jzp820927** [comment]
好的，谢谢！

**Comment by jzp820927** [comment]
再请教一个问题，我看到 test_script/config.json 里面的默认配置，有一项是：
  "mapping": {
    "dns.google.com": "8.8.8.8"
  }
难道 8.8.8.8 也支持 DNS over HTTPS？我测了一下，8.8.8.8 的 443 端口都没开放，有点不解，求解惑？谢谢！

**Comment by ayanamist** [comment]
这是让指定域名及其子域名使用指定的普通dns。

**Comment by jzp820927** [comment]
哦，是不是类似于 dnsmasq 的 server 配置？理解错误，我还以为是 hosts 。

**Comment by ayanamist** [comment]
是的，类似dnsmasq的server配置项

**Comment by jzp820927** [comment]
懂了，谢谢解答！
