### ISSUE TITLE
有没有考虑过支持 QUIC？

### ISSUE THREAD

**Issue by jzp820927** [ayanamist/gdns-go#6]
目前已经支持通过 HTTP/2 来提高查询性能，我在想，是否能通过 QUIC 进一步提高性能？

**Comment by ayanamist** [comment]
没有计划，QUIC目前没有成熟的实现。

**Comment by jzp820927** [comment]
好吧，我就随口一问。

**Comment by jzp820927** [comment]
https://github.com/lucas-clemente/quic-go/
好像没更新了，不知道还有没有继续开发的计划？

**Comment by ayanamist** [comment]
噢，明白了。看起来很简单，但我个人觉得价值不大，udp协议在国内被管制的很厉害，反而效果不好。我看替换个transport就可以了，你可以自己试试效果然后提个PR。

**Comment by jzp820927** [comment]
额，go 语言一窍不通，看看如果有能力了，我就来提 PR 吧，谢谢。
