### ISSUE TITLE
go get 遇错

### ISSUE THREAD

**Issue by luckypoem** [ayanamist/gdns-go#7]
hi，
我在mac上运行go get -u -v github.com/ayanamist/gdns-go
遇错：
...
github.com/ayanamist/gdns-go
# github.com/ayanamist/gdns-go
src/github.com/ayanamist/gdns-go/error.go:47:7: undefined: dns.ErrTruncated
怎么解决？

**Comment by ayanamist** [comment]
这个函数没用了，我删掉了，你重试下

**Comment by luckypoem** [comment]
谢谢答复。现在ok了。
另外我看到你也fork了node-spdyproxy：
https://github.com/ayanamist/node-spdyproxy ，不过我安装它后，运行命令遇错：
https://github.com/igrigorik/node-spdyproxy/issues/68 ，请问如何解决这问题？
你现在还能用node-spdyproxy翻墙吗？
 
真是不好意思，在这里问这个问题，因为没其他联系方式。请见谅。
非常感谢答复

**Comment by ayanamist** [comment]
四年前fork的，早就不用了
