### ISSUE TITLE
请问能不能用ssr代替ss

### ISSUE THREAD

**Issue by chuangdi** [ayanamist/gdns-go#8]
如果能用ssr代替ss就太好了，我看了下源码好像只有dialer.go调用了ss，请问能否用ssr代替ss进行dns的查询。

**Comment by ayanamist** [comment]
没有成熟的ssr go支持

**Comment by chuangdi** [comment]
https://github.com/sun8911879/shadowsocksR，这个难道不行吗？

**Comment by chuangdi** [comment]
https://github.com/sun8911879/shadowsocksR，这个难道不行吗？

**Comment by ayanamist** [comment]
试过，并不稳定
